name: Build and Deploy to Docker Hub & Render

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Definimos secretos como env para validarlos y evitar advertencias en VS Code
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      IMAGE_NAME: hola-docker

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Validate required secrets
      run: |
        for v in DOCKER_USERNAME DOCKER_PASSWORD RENDER_API_KEY RENDER_SERVICE_ID; do
          if [ -z "${!v}" ]; then
            echo "::error::Missing required secret: $v"
            exit 1
          fi
        done

    - name: Sanitize Docker username
      run: |
        CLEAN_USER=$(echo "$DOCKER_USERNAME" | sed 's|^/||' | tr -d ' ')
        if [ -z "$CLEAN_USER" ]; then
          echo "::error::DOCKER_USERNAME is empty after sanitizing"
          exit 1
        fi
        echo "DOCKER_USER=$CLEAN_USER" >> "$GITHUB_ENV"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64
        tags: |
          ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Trigger Render deploy
      run: |
        curl -fsSL -X POST                   -H "Accept: application/json"                   -H "Authorization: Bearer $RENDER_API_KEY"                   -H "Content-Type: application/json"                   --data '{"clearCache": false}'                   "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys"
