name: Build and Deploy to Render

on:
  push:
    branches:
      - main  # o la rama que uses

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: bluesun777/hola-docker:latest

      - name: Trigger Render Deploy
        run: |
          echo "Calling Render Deploy Hook..."
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
